### ISSUE TITLE
Remove all STH-backed nodes in production

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#1041]
Move all prod instances to the more efficient PebbleDB backed system. Expect ~50% cost savings

**Comment by masih** [comment]
Total of 8 nodes were torn down over the last 2 weeks see list [here](https://github.com/filecoin-project/storetheindex/pulls?q=is%3Apr+is%3Aclsoed+retire+). Only one more node remains that uses STH-backed node: `vega` in prod. It is in healthy state though has consumed over 85% of its [40Ti](https://github.com/filecoin-project/storetheindex/blob/main/deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/pvc.yaml#L8) storage.
