### ISSUE TITLE
Optimise handing of batch advertisement

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#124]
Allow the indexer node to efficiently handle a batch of advertisements received at once from a provider by:
- calculating the diff of changes first,
- then resolving the entry chunks.

This means in a batch of advertisements if a chunk is added in an earlier advertisement then removed in a later one, should not bother fetching the multihashes.

This can tie into rate-limiting story in the indexer, where an approach could be: advertisements are collected in a time-window and are processed at once with some constant rate.

Cc @gammazero 

Relates to:
* https://github.com/filecoin-project/storetheindex/pull/105#issuecomment-979249687

**Comment by masih** [comment]
Reposting comment here for visibility:
> ...queue advertisements and process them in batch when either a timeout has elapsed or the queue grows larger than a value; this is so that we automatically, and always batch process for a more efficient syncing mechanism. You can imagine the strategy for batch processing the advertisements can then grow to "group by X", where X can be provider, geo-location, score, etc. This is the stuff that would be useful to talk about in the context of indexer node scalability.

**Comment by MarcoPolo** [comment]
Could you elaborate on how this would be more efficient than processing the ads one at a time?

The only cases where you would do less work are (from what I understand):
* An earlier Advertisement adds something, and a later one removes it (within a batch).
* Multiple Ads (within a batch) reference the same entry chunk (since we currently delete the chunk after processing).

Any other cases?

**Comment by masih** [comment]
That's it I think. The main motivation for capturing this ticket is the first case.

Re second case, the code should always check that it has a root entries link locally before opening a graphsyc pull channel so doing one at a time or batching should cover that anyway unless I am missing something :)

**Comment by gammazero** [comment]
I think this will mostly only be seen by new indexers coming online.  Ones that are running will typically be keeping up with each individual advertisement.  If the maximum length of an advertisement chain is limited, this may not be worth solving.
