### ISSUE TITLE
Separate library and command go modules

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#130]
In order to reduce the dependency footprint of the storetheindex, separate the portion of code used as a library that `index-provider` depends on, from the portion of code used to run an indexer node as a service.

**Comment by gammazero** [comment]
A go module is a set of packages versioned together.  Splitting the service code and the lib (api) code into separate modules will separate their dependencies, and should allow them to be versioned separately.  However, version tagging is generally applied to a Github repo, not to separate modules within the repo.  Therefore, if we need to have these as separate modules, then I think we should create a separate `storetheindex-api` repo. That will allow the api code to be cleanly versioned separately from the service code.

**Comment by masih** [comment]
> However, version tagging is generally applied to a Github repo, not to separate modules within the repo. Therefore, if we need to have these as separate modules, then I think we should create a separate storetheindex-api repo.

Go supports a single repo with multiple modules along with mechanisms to associate tags with specific modules located at subdirectories. See:
* https://go.dev/ref/mod#vcs-version

Considering the number of repos already associated with indexing, my vote would be to avoid creating a new repo.

**Comment by gammazero** [comment]
@masih I do not think this is a problem with go1.17+. Please close if there are no remaining problems.
