### ISSUE TITLE
Sync advertisements DAG selectively

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#136]
When syncing an advertisement use a selector, such that:
* the traversal stops at the latest seen advertisement
* the chunks are excluded

Exclude the chunks so that:
* linksystem can be checked for its presence before pull channel is opened.
* we reduce unnecessary traffic in cases where multiple providers provide the same CAR content.

For syncing the chain of entries a full traversal via explore all selector is permitted, as long as the link system is checked for the root of entries chain prior to open pull channel.

**Comment by willscott** [comment]
is this the same as #124 ?

**Comment by masih** [comment]
I don't think its though they relate. This issue is about simply integrating selectors into advertisement syncing. #124 is about an optimisation for a use case that we don't know how popular it would be but a valid optimisation nonetheless, where If we encounter a long chain of unseen advertisements we can be more efficient about how to sync them; i.e. calculate total diff then sync the chunks rather than dept-first entry chunk syncing. 

Aside from the use case in #124, in my opinion makes sense to queue advertisements and process them in batch when either a timeout has elapsed or the queue grows larger than a value; this is so that we automatically, and always batch process for a more efficient syncing mechanism. You can imagine the strategy for batch processing the advertisements can then grow to "group by X", where X can be provider, geo-location, score, etc.  This is the stuff that would be useful to talk about in the context of indexer node scalability.

Cc @gammazero
