### ISSUE TITLE
Periodically check for provider responsiveness and delist dead providers

### ISSUE THREAD

**Issue by gammazero** [filecoin-project/storetheindex#144]
Periodically check that a provider is responding to requests for data.  After some configured amount of time of unresponsiveness, delist the provider.

The purpose of this is to stop returning indexer responses for dead providers, as this will cause clients to waste time by attempting to retrieve data from dead providers.

Sufficient warnings should be generated so that an administrator can take any necessary action before a provider is delisted.

**Comment by willscott** [comment]
this is fixed with #442
