### ISSUE TITLE
More efficient Advertisement signature

### ISSUE THREAD

**Issue by MarcoPolo** [filecoin-project/storetheindex#165]
I believe https://github.com/filecoin-project/storetheindex/issues/58 is related.

As it is right now a signature is over half the total advertisement. That's because we're signing the concatted bytes of the adv and storing that in the signature field.

I think we should be signing the hash of the relevant fields so we only sign a hash. Concretely:
1. Calculate the multihash of concating all the fields with some separator ":". Essentially get the bytes for every field join them with the ":" and pass it into to: https://pkg.go.dev/github.com/multiformats/go-multihash#Sum. 
2. Sign this multihash with envelope (as it is now).
3. Insert this into the signature field.

On verification:
1. Open the envelope.
2. Learn about the type of hash from the multihash.
3. Hash the fields the same as before.
4. Verify the multihash matches.

**Comment by gammazero** [comment]
Fixed by #188
