### ISSUE TITLE
Indexer needs some retry strategy for failed syncs

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#172]
If a provider fails during sync the indexer simply suspends the sync. It will not retry again until publication of a new head reaches it through gossipsub, or until it has been long enough since there have been any updates for a provider. 

It would make sense to engineer some retry mechanism to sync indices from providers when an error occurs during sync. 

For retry logic consider circuit breaker pattern or a simple exponential backoff.

**Comment by gammazero** [comment]
> visit known providers that indexer has not heard from

The advertisement publisher can be different from the provider.  This leads to some items to clarify:
1. Do you mean that the indexer should visit publishers it has not heard from in a long time? Or, do you mean that the indexer should visit the publisher(s) for those providers it has not received any updates for in a long time?
2. If there have been no updates for a provider for a long time, and the provider has multiple publishers, should the indexer visit all of the publishers?

**Comment by willscott** [comment]
closing as deprecated - the legs mechanism now handles this reasonably well
