### ISSUE TITLE
Pointer to head advertisement is updated before processing of entries finish

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#174]
Pointer to head ad is updated before processing of entries finishes (this is entries of the head ad or its previous ads). 

As a result if syncing of entries fail, say due to intermittent connection issue, or indexer restart, those entries will never be synced again. 

Manual sync will also not work because of the reference to latest matching the current head. 

Note that not updating the head is not enough to make sure a chain of entries is fully synced. because right now we only check the local datastore for root entries chain before syncing over graphsync. So if a chain of entries is partially synced, as long as its root is synced the logic thinks that the entire chain is present.

**Comment by gammazero** [comment]
Fixed by #180 and #190
