### ISSUE TITLE
Investigate consistency of calls to `StorageWriteOpener` and `IncomingBlockHook`

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#175]
The advertisement entry processing logic is spread across two components:
* [`StorageWriteOpener`](https://github.com/filecoin-project/storetheindex/blob/09d121b7700e3c8557457173f807e1bf776267be/internal/ingest/linksystem.go#L62) , and 
* [`storageHook`](https://github.com/filecoin-project/storetheindex/blob/09d121b7700e3c8557457173f807e1bf776267be/internal/ingest/linksystem.go#L220)

Considering the above;
* Is it possible for one to be called but for the other to not be called?
  For example, if a cid is already present in the datastore/linksystem but synced over graphsync. Or if a component returns err.
* If so, would the processing logic continue to work correctly when that happens?

Consider moving as much of the logic to one place as possible to avoid this kind of edge cases.

**Comment by gammazero** [comment]
Investigated by @MarcoPolo and resolved by #180
