### ISSUE TITLE
If port is missing the finder client always uses hardcoded default port

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#184]
If the port number for HTTP APIs is not specified, the client library always falls back to a hardcoded default which:
1. may be different from the configured port at runtime, and
2. makes assumptions about how the endpoint is exposed. 

For example, to use the indexer nodes in K8S environments which set up to use `cid.contact` name servers, the address `cid.contact` for indexer server will not work, and instead the user is forced to specify the address as `cid.contact:80` when using the client SDK.

Consider simplifying the logic and remove fallback on hardcoded defaults. This would cause the HTTP package to do the right thing and pick the default port depending on protocol.

https://github.com/filecoin-project/storetheindex/blob/440e2f005ffd65d21e531bcdb070487c9153bd68/api/v0/httpclient/client.go#L30-L32

**Comment by gammazero** [comment]
Fixed by #254
