### ISSUE TITLE
`provider list` address and latest advertisement CID is inconsistent with latest sync

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#193]
EC2 Indexer node is already synced to the latest advertisement `baguqeeqq7h34repxmkzsqmqadbb6ckk6fi` of the Sofia miner. (confirmed via explicit sync, with logs showing `Already Synced`):

```
$ storetheindex admin sync -p 12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ
2022-01-31T11:25:24.254Z        INFO    go-legs go-legs@v0.2.7/subscriber.go:396        Start sync      {"peer": "12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ", "cid": "baguqeeqq7h34repxmkzsqmqadbb6ckk6fi"}
2022-01-31T11:25:24.254Z        INFO    go-legs go-legs@v0.2.7/subscriber.go:592        Already synced  {"cid": "baguqeeqq7h34repxmkzsqmqadbb6ckk6fi", "peer": "12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ"}
```

The latest advertisement has the retrieval address `/ip4/85.11.148.122/tcp/24001`:

```shell
$ provider list -p '/ip4/85.11.148.122/tcp/24002/p2p/12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ' baguqeeqq7h34repxmkzsqmqadbb6ckk6fi
ID:          baguqeeqq7h34repxmkzsqmqadbb6ckk6fi
PreviousID:  baguqeeqqiutgwhih26ak3xo4kop6ewuv3q
ProviderID:  12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ
Addresses:   [/ip4/85.11.148.122/tcp/24001]
Is Remove:   false
Entries:
  Chunk Count: 1
  Total Count: 14144
```

But when listing providers through indexer node, the address associated to the Sofia miner provider as well as the `LastAdvertisement` ID seems inconsistent with the latest synced and points to earlier advertisements:

```
$ storetheindex providers list
Provider 12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ
    Addresses: [/ip4/192.168.0.109/tcp/39383]
    LastAdvertisement: baguqeeqq7yf6qlnw277zx6w2ssbn5vpxdi
    LastAdvertisementTime: 2022-01-26T14:29:48Z

```

The address shown above is indeed the address that was in `baguqeeqq7yf6qlnw277zx6w2ssbn5vpxdi` advertisement and is the wrong one. But since then the problem has been fixed and many advertisements were published with correct address which seem to have already been synced by the indexer.

What is missing?

**Comment by willscott** [comment]
while you're looking at this logic again, it may be worth also understanding if we can/are properly handling deduplication/removal logic of not fetching the content for an advertisement that is more recently removed from the chain
