### ISSUE TITLE
Prune no longer allowed providers from registry during load

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#194]
If a provider was once registered in registry but it gets removed from the list of allowed providers, its registration record will remain in the registry datastore indefinitely.

Consider checking the policy for each of the loaded providers and prune any that are no longer allowed during load:

https://github.com/filecoin-project/storetheindex/blob/e948c49137f512fa2971fddeb696f1a5f57e870b/internal/registry/registry.go#L479

**Comment by gammazero** [comment]
This seems like a good thing to do, but it also seems dangerous.  If someone were to start up their indexer with the wrong config file, or with a new config file that was not properly configured, then that indexer could lose some or all of its data.

I think before deleting someone's data, there needs to be a confirmation that they intend to do so.

What about on startup only excluding adding disallowed providers back into the registry, and excluding unregistered providers from indexer responses, while leaving the saved registry data and content in storage for those providers.  That way if they are allowed again, all their data becomes available again.

A separate indexer command can be used to remove specific providers, or all unallowed providers, and will require confirmation to delete data.

**Comment by gammazero** [comment]
Handled by #195.  Do we need a new command to purge indexed content as well?

**Comment by masih** [comment]
> Do we need a new command to purge indexed content as well?

If we do that should go to another issue I imagine.
