### ISSUE TITLE
indexer may re-index previously indexed advertisements

### ISSUE THREAD

**Issue by MarcoPolo** [filecoin-project/storetheindex#204]
We don't currently track that we've ingested an Ad so we may re-index it in the future if we run into the Ad again.

I think at a high level the indexer should gaurantee that if it has process some Ad `C` it has also processed all ads below that and will not reprocess Ad `C` again.

Reprocessing a previously indexed Ad could lead to inconsistency across indexers. And it may lead to rewinding a newer Ad.

For example we may have a publisher that pushes:
```
A <- B <- C (isRm=true; rm entries in B)
```
Some time passes and we process A,B,C.

Then another publisher may then set their head to be B:
```
A<-B
```
Now the indexer will re-process A,B. So now we undid the change of C.

**Comment by gammazero** [comment]
Every ad is now marked as processed:
https://github.com/filecoin-project/storetheindex/blob/main/internal/ingest/ingest.go#L397

And will be avoided if encountered again from a different publisher:
https://github.com/filecoin-project/storetheindex/blob/main/internal/ingest/ingest.go#L385
https://github.com/filecoin-project/storetheindex/blob/main/internal/ingest/ingest.go#L586-L589
