### ISSUE TITLE
Checking ad provider ID matches signer peer ID is never false if signature verification passes

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#257]
A [check](https://github.com/filecoin-project/storetheindex/blob/9d30817b79093fc0b86f7c9b851f473b9e7c8c5e/internal/ingest/linksystem.go#L124) is performed to assert that the signer of an envelop matches the provider of an advertisement.

But, the signature verification logic [will fail ](https://github.com/filecoin-project/storetheindex/blob/main/api/v0/ingest/schema/envelope.go#L154) otherwise anyway because it requires `advID` across envelops to match, and the ad [provider ID is included](https://github.com/filecoin-project/storetheindex/blob/main/api/v0/ingest/schema/envelope.go#L76) in the `advID` calculation. This makes the check referenced above to be always false, since a verified signature by definition must mean provider IDs must have matched.

Consider, either removing that check completely or relax the need for  `provider ID`s to match across envelops during signature verification.

**Comment by gammazero** [comment]
The [`VerifySignature`](https://github.com/filecoin-project/storetheindex/blob/9d30817b79093fc0b86f7c9b851f473b9e7c8c5e/api/v0/ingest/schema/envelope.go#L125) checks that the advertisement was signed by the private key that matches the public key that is included in the envelope.  However, an advertisement could be constructed where this public key is different than the provider ID in the advertisement.  Therefore it is still necessary to check that the identity (public key) used to sign the advertisement is the ID that we wanted to sign the advertisement, which currently is the provider ID.

**Comment by masih** [comment]
That makes sense thanks @gammazero  🍻
