### ISSUE TITLE
Set limit for the maximum size of metadata accepted by the indexer

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#261]
The indexer node already has a size limit for for [ContextID](https://github.com/filecoin-project/storetheindex/blob/main/api/v0/ingest/schema/utils.go#L59).

Consider introducing a similar limitation for metadata for resilience.

**Comment by gammazero** [comment]
Metadata will typically contain a unique ID that is specific to the provider (such as deal ID), and possibly a few other parameters.  I think the length of this value should be at most 1KiB.

In the interest of indexer interoperability, I would prefer that this is not configurable.  If this is configured differently on different indexers, the one with the smaller limit may not be able to index the same content as the one with the larger limit.  Also, a provider may not be able to use all indexers if some are configured with a very small metadata size limit.
