### ISSUE TITLE
`/metrics` instantiates a prometheus exporter every time it is called

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#271]
https://github.com/filecoin-project/storetheindex/blob/3c034d3e530969681c566fc4714c30e27523fd8a/server/admin/http/server.go#L73

**Comment by gammazero** [comment]
Actually this line does not create a new metrics exporter every call.  The call to `metrics.Start(coremetrics.DefaultViews)` is returning the handler function to use.

**Comment by masih** [comment]
You are right my bad
