### ISSUE TITLE
Update production configuration to run 2 full STI replicas to reduce downtime during updates

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#285]
When redeploying the Indexer, it can take up to 5 minutes to fully restart the service. This will only increase as the Index grows. Add another replica to handle read traffic and minimize downtime for the Network Indexer service.

**Comment by masih** [comment]
This is done I believe.

**Comment by masih** [comment]
Readiness check is added to the helm chart and configured in lotus infra to take advantage of multiple deployments, and avoid disrupting service during rollout. See:
* https://github.com/filecoin-project/lotus-infra/pull/617
* https://github.com/filecoin-project/helm-charts/pull/139
