### ISSUE TITLE
Maintain a snapshot of STI on EBS

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#288]
Adding a snapshot backup will provide redundant data in case of machine corruption and enable new STI instances to sync to the latest state of the network faster.

**Comment by davidd8** [comment]
@gammazero do you want to update this ticket, add any more details to help prioritize?

**Comment by gammazero** [comment]
I think we can close this. Having multiple indexers with their own copy of the index data should negate the need to keep a snapshot.

**Comment by gammazero** [comment]
Closing since we are running multiple indexers.
