### ISSUE TITLE
Update production configuration to run in multiple AZs

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#289]
Running the Network Indexer in multiple AZs will provider more fault tolerance from network outages and help improve performance for different regions.

**Comment by masih** [comment]
This happens now on the infra we own. I don't think it's worth trying to roll it out to fil infra. 

Please re-open if you think otherwise.

**Comment by masih** [comment]
Also see: https://github.com/filecoin-project/storetheindex/pull/401
