### ISSUE TITLE
Investigate EFS to create read-only STI replicas

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#290]
Since EFS allows read-write-many semantics, this could enable the running of read-only STI replicas to horizontally scale to handle read traffic and avoid saturation of the network for ingestion. Read-only replicas should be a lot faster to deploy as well.

**Comment by masih** [comment]
No longer applies because:
* volumes are migrated to use `io2` with `ReadWriteOnce` mount type.
* `io2` volumes do not support `ReadWiriteMany`. See: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/449
