### ISSUE TITLE
Create Production GitOps Cluster

### ISSUE THREAD

**Issue by MarcoPolo** [filecoin-project/storetheindex#302]
Tracking ticket for making a production-grade gitops-backed cluster.

We have a dev version of it defined in https://github.com/filecoin-project/storetheindex/tree/main/deploy. So the tasks are:

1. Verify that deploy/setup seems reasonable.
2. Help us set up a production version of that cluster.

Feel free to make sub issues that break this task further

**Comment by masih** [comment]
Fixed by: 
* #337 
* #340
