### ISSUE TITLE
Have infra bootstrap nodes know about nodes on new GitOps cluster

### ISSUE THREAD

**Issue by MarcoPolo** [filecoin-project/storetheindex#303]
Before we migrate fully to our own GitOps prod cluster we need to add the identity of the gitops prod nodes to the infra bootstrap nodes so that they get connected to the pubsub mesh.

**Comment by MarcoPolo** [comment]
See https://github.com/filecoin-project/lotus-infra/pull/560 for prior art. It should be just extending the array to add more peer ids.

**Comment by masih** [comment]
Done in https://github.com/filecoin-project/lotus-infra/pull/647
