### ISSUE TITLE
Connect metrics in gitops deploys to grafana

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#304]
we don't currently have piping for collecting metrics from storetheindex in the deployment managed by gitops and tracking it somewhere observable.

**Comment by masih** [comment]
Duplicate of https://github.com/filecoin-project/storetheindex/issues/372
Note that metrics are collected from instances running in our own AWS account. they are just not forwarded to PL grafana.

Closing; please feel free to reopen if I missed anything.
