### ISSUE TITLE
Add Prometheus to cluster

### ISSUE THREAD

**Issue by MarcoPolo** [filecoin-project/storetheindex#305]
(and optionally grafana so that we can view the metrics without having to hook up to grafana cloud right away).

In production we still need prometheus in our cluster, and the PL grafana cloud will query our cluster's prometheus for metrics.

**Comment by masih** [comment]
Full monitoring stack is set up in each cluster via #325. 

Awaiting response from ops to see what steps we need to take to have the monitoring information fed back to PL grafana.

**Comment by masih** [comment]
There is an issue for connection to PL grafana here: https://github.com/filecoin-project/storetheindex/issues/372

Closing since having our own grafana +prometheus stack is already resolved.
