### ISSUE TITLE
Create a public Notion Page to show all public Network Indexers

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#315]

**Comment by gammazero** [comment]
https://www.notion.so/pl-strflt/Network-Indexer-Nodes-4fb050e5db3b4513b72e055c0df3510d

**Comment by davidd8** [comment]
https://www.notion.so/pl-strflt/Directory-Network-Indexer-Nodes-1e894aa158934c44a9e90b5df255e68e
