### ISSUE TITLE
Create a notion page describing the hardware requirements to run an Indexer Node

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#373]
This should help guide folks that want to run a global indexer node, or a more local indexer node. Once the system requirements are well established, we can update the README on github

cc @gammazero @LexLuthr

**Comment by honghaoq** [comment]
I created a partner guide notion page for running indexer node, should we add it here as a new section / subpage? 
https://www.notion.so/pl-strflt/Running-Indexer-Node-Partner-Guide-7aa65013b8b4410db743a13b5865afca 
@gammazero @LexLuthr
