### ISSUE TITLE
Publish Indexer Node FIP

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#375]

**Comment by davidd8** [comment]
@honghaoq any updates here?

**Comment by honghaoq** [comment]
PR is created on FIP repo: https://github.com/filecoin-project/FIPs/pull/341 

Working with Kaitlin to arrange the Core dev call to review and discuss FIP together this Thursday. I will forward the invite to our team.

**Comment by honghaoq** [comment]
Thursday review invite forwarded @davidd8 @willscott @gammazero. Meeting title: core dev review (one on 9am PT, another one on 4pm PT)

**Comment by davidd8** [comment]
Thanks @honghaoq!

**Comment by honghaoq** [comment]
https://github.com/filecoin-project/FIPs/pull/365

**Comment by honghaoq** [comment]
The work from indexer side is completed. FIP approved for merge, Kaitlin will publish it as FRC.
