### ISSUE TITLE
Add aws "tags" to delineate storetheindex costs

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/storetheindex#415]
Currently, STI and autoretrieve are under the same AWS account. Let's add tags to have a clear breakdown of costs as both services scale in production.

**Comment by masih** [comment]
All Storetheindex resources are consistently tagged across both dev and prod environments via terraform. See:
- `dev` [tags](https://github.com/filecoin-project/storetheindex/blob/main/deploy/infrastructure/dev/us-east-2/locals.tf#L8-L14)
- `prod` [tags](https://github.com/filecoin-project/storetheindex/blob/main/deploy/infrastructure/prod/us-east-2/locals.tf#L8-L14)

All resources belonging to storetheindex are created using terraform.

Closing. 
Please re-open if I am missing something.
