### ISSUE TITLE
Increase AWS Elastic IP limit

### ISSUE THREAD

**Issue by steve-fraser** [filecoin-project/storetheindex#443]
We are in the process of deploying a new dev cluster for that is fully gitops.

We hit an Elastic IP limit in the storetheindex account while trying to bring it up.

```
failed to create one or more IP addresses for NAT gateways: failed to
      allocate Elastic IP: AddressLimitExceeded: The maximum number of addresses has
      been reached
```

We need to the limit increased.

**Comment by masih** [comment]
Quota increase requested.

**Comment by masih** [comment]
Resolved by quota increase. Please reopen if there is anything I have missed.
