### ISSUE TITLE
HTTP sync of large advertisement chains causes out of memory

### ISSUE THREAD

**Issue by gammazero** [filecoin-project/storetheindex#487]
When fetched over HTTP, very long advertisement chains cause out of memory very quickly compared to over graphsync.

Comment from @masih :
> we run out of memory very quickly for long chains synced via HTTP.  In order to implement the selector mechanism over HTTP, we are using traversal.Progress [here](https://github.com/filecoin-project/go-legs/blob/main/httpsync/sync.go#L186).  That type keeps updating an internal field called Path with whatever path it comes across. Eventually that path grows massive when the recursion depth is unlimited. That path is stored in memory.
> 
> Breaking up calls to `progress.Walk` won’t help since even if we resume we need the path to tell it where to resume from.
So i think we need to break up sync in the storetheindex level since the application knows what the node types are  and it can then instantiate a new sync say from an ad’s previous ID having synced all its entry after some configurable depth

**Comment by masih** [comment]
Being tested on `dev`; deployment on prod pending.

**Comment by masih** [comment]
Fixes are released and deployed on prod.
