### ISSUE TITLE
Why interfaces work with CIDs when only multihash is used for indexing purposes

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#49]
The ingestion and finder schemas use CIDs. But only the multihash within a CID is used for matching, and the codec in CIDs is ignored. 

If the codec is never used by the indexer node, would it make sense for both the data provider and finder interfaces to only work with multihashes?

**Comment by mikeal** [comment]
+1, I’m concerned that having the protocol use CID’s but the implementation operate on multihash is destined to cause implementations to differ. If we want the **protocol** to operate on multihash then we should put it up front.

**Comment by gammazero** [comment]
Resolved by #83 and related design doc updates to use multihash instead of CID
