### ISSUE TITLE
Ingestion: don't ask for cid lists of retracted indexes

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#53]
When walking back from the head of an index announcement chain, if the indexer encounters a notice of retraction of a previous index, and then later encounters the previous index, it should not ask for the list of CIDs composing that previous index. Since the index has been removed, the provider may not have it any more, and will not reliably be able to supply the CID list anymore.
We should either not fail everything and ignore the failure, or not ask for the CID list at all

**Comment by willscott** [comment]
Right. there will be an error expected, since the provider will not have the data anymore, but in the common case the indexer can know not request it, since in playing back the log from the most recent, it should have seen in the retraction from the same provider before seeing it advertised

**Comment by gammazero** [comment]
Fixed by #553
