### ISSUE TITLE
Invalid multihashes are ingested and discoverable

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#539]
Advertisements with invalid multihash are ingested as normal by the indexer and are discoverable. I am not sure how important this is but wondering if an assumption that bytes in entry chunks are all multihashes could cause problems internally, or maybe at upstream services?

Test that confirms this is [here](https://github.com/filecoin-project/storetheindex/blob/masih/test-invalid-mh-ingestion/internal/ingest/invalid_mh_ingest_test.go).

**Comment by gammazero** [comment]
Fixed by #555.  Bad multihashes are now excluded from ingestion.
