### ISSUE TITLE
Ingestion: Sync with provider advertisement by advertisement

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/storetheindex#56]
To prevent providers from having to load in memory all the data required for syncing (especially if the indexer is outdated for a few dozen or hundreds of advertisement, or it needs to sync with a provider from scratch), the syncing protocol should be implement so that instead of using a single selector to ingest all the pending nodes in the chain at once, it makes individual requests for each advertisement until it fully syncs. This way, the provider only needs to load in memory the equivalent content for one advertisement at a time.

To support this kind of syncing approach, we'll need to change `PreviousID` in `Advertisement` to a Link, and we may need to implement a recursion condition (as described [here](https://github.com/ipld/go-ipld-prime/issues/237)) which prevents further recursion for certain fields in a Node.

**Comment by adlrocha** [comment]
Update on this issue:
- Since the issue was posted we've changed the `Advertisement` schema. The step-by-step sync will now look something like this:
    - We first perform a `ExploreRecursive` selector with a `stopAt` in the indexers latest sync following only the `PreviousID` field to get all the pending advertisements pending to fully sync. For each advertisement we get the `Entries` link.
    - We then use a selector to get the `Entries` link which will lead to the ingestion of the list of entries (as a linked list in the latest schema).
    - To achieve this we'll need to perform independent calls to `Fetch` over the hosts `LegTransport` (https://github.com/willscott/go-legs/blob/ba1acdbce460beb27f31668d875303a7cc7975fc/transport.go#L102). We'll need to add additional state to track what has been synced, what is pending, etc. `go-legs` subscribers currently trigger the `ExploreRecursive` with stop to ingest everything, with this approach they should trigger the download of the advertisement, and is the indexer Ingester the one that needs to handle and orchestrate the actual ingestion of the list of multihashes.

I personally found it easier to use for this an `ExploreRecursive` selector with a `bypass` condition (in [this PR](https://github.com/ipld/go-ipld-prime/pull/240) and not merged to `go-ipld-prime`, but apparently we can achieve the same behavior with the already existing `ExploreFields` selector. I am still trying to figure out how to make it work.

**Comment by gammazero** [comment]
@masih Seems like this was taken care of by #139 and others.  Please close if done.

**Comment by masih** [comment]
@gammazero I think what #139 does is slightly different: It recursively syncs advertisements starting from one after last seen to the latest. For each of those unseen advertisements it then syncs entries chain. The syncing of entries is done via storage hook trigger. 

What's proposed here is stopping at every advertisement to sync entries, where each advertisement would open a new data transfer pull channel.

Apologies for sounding a bit pedantic; I want to make sure there wasn't anything that we missed in #139 with regards to this issue.

What are your thoughts?

**Comment by gammazero** [comment]
I think #139 accomplishes all the goals of this issue.  If you agree, lets close this.

**Comment by gammazero** [comment]
This is implemented.  The indexer reads the chain of advertisements, and then for each one, from earliest to latest, does a separate sync of the content entries chain.
