### ISSUE TITLE
Avoid using config specific structures on public interfaces

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/storetheindex#61]
I was implementing the push of individual CIDs to the indexer in the reference provider, and I had to build a config-specific `cfg.Identity` structure to be able to use the function. We should probably avoid using config-specific structures for public interfaces and accept `privKey` and `peer.ID` as arguments.

https://github.com/filecoin-project/storetheindex/blob/8ff562c1bc9a6295fe705c6ade81b5a0ba13247d/api/v0/ingest/client/libp2p/client.go#L95

//cc @gammazero

**Comment by gammazero** [comment]
This was fixed in #83
