### ISSUE TITLE
cloudfront is stripping headers

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#612]
The internal golang server sets some relevant headers, e.g. https://github.com/filecoin-project/storetheindex/blob/main/internal/httpserver/util.go#L17-L19

These are not returned to clients, and appear to be removed at the cloudfront level.
We need to allow them through in order to get expected JS api access and caching.

**Comment by masih** [comment]
This is not a cloudfront issue. The finder server does not seen to return the headers set as part of response handling. Digging deeper. I think this is a gorilla/mux issue

**Comment by masih** [comment]
The finder server responses are fixed and deployed in `dev`. It'll take a bit of time for the deployment to roll out. Once that's done, I'll pick this issue back up, there may be changes we need in cloudfront too. Unclear until deployment rollout is complete.

**Comment by masih** [comment]
It looks like the changes in code did the trick, no need for cloudfront changes. see CORS test [here](https://cors-test.codehappy.dev/?url=https%3A%2F%2Fdev.cid.contact%2Fstats&method=get)

The response content type is now fixed too:

```bash
$ curl -sSL -D - https://dev.cid.contact/providers -o /dev/null        

HTTP/2 200 
date: Thu, 04 Aug 2022 15:17:43 GMT
content-type: application/json; charset=utf-8
access-control-allow-methods: GET,OPTIONS
access-control-allow-origin: *
strict-transport-security: max-age=15724800; includeSubDomains
```
