### ISSUE TITLE
Faster startup times

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#617]
We notice on dev that:
> 144m since deploy and first pod is still scanning.

we have rolling upgrades now, so service isn't impacted, but if we ever find a crashing bug we're going to want to be able to upgrade the software with less than several hours of downtime.

**Comment by masih** [comment]
A potential approach is to break up the sth datastore with some sticky heuristic to deterministically pick datastore based on ingest request. 

That would then allow us to scan datastores in parallel and hopefully reduce the startup time as well as enabling partial availability.

**Comment by gammazero** [comment]
This should be fixed by the new index-gc, available with v0.4.21. When storetheindex has a clean shutdown the next startup time on only a second or two.  When there is not a clean shutdown, the startup time is significantly faster as deleted record spans are skipped when scanning index files.

**Comment by gammazero** [comment]
Fixed by current version of sth that saves memory state clean shutdown. On the next startup, this data is read back into memory instead of scanning all the index files.
