### ISSUE TITLE
Maximum number of finder connections should be configurable in config file

### ISSUE THREAD

**Issue by gammazero** [filecoin-project/storetheindex#632]
There is an existing option [here](https://github.com/filecoin-project/storetheindex/blob/main/server/finder/http/options.go#L31), but needs a function to set the option.

**Comment by arnabguin** [comment]
I noticed that the finderOpt is only updated with the home page currently. Wanted to know if this issue also encompasses adding an option in the config file.
finderOpt := httpfinderserver.WithHomepage(cfg.Addresses.FinderWebpage)

**Comment by willscott** [comment]
yes, it probably should include that connection to the config file. Thanks, @arnabguin
