### ISSUE TITLE
Remove dependencies on models / exported types packages

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#65]
looking at using the http request/response in prototyping a client.
it pulls in a bunch more dependencies than i'd hope it would.

e.g. https://github.com/filecoin-project/storetheindex/blob/94c90bbf80e1f2f4335a371f4653b0117005a7b7/api/v0/finder/models/models.go#L8

**Comment by gammazero** [comment]
Fixed by #85
