### ISSUE TITLE
Implement signing mechanism for families of providers

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#678]
We see cases where providers:
* want to provide different data protocols at different endpoints
* want an alias at a new node with a new identity

we should be able to handle these cases efficiently. To do so we need:
* signing from both identities
* message indicating the additional identity being added / removed

**Comment by willscott** [comment]
A design is at https://github.com/filecoin-project/storetheindex/pull/804

This issue should now track implementation of the spec

**Comment by momack2** [comment]
Is work happening against this somewhere? AFAIK this is going to be completed and launched by EOQ - correct?

**Comment by willscott** [comment]
yes
@ischasny  has implemented this - it's in [v0.9.2](https://github.com/filecoin-project/index-provider/releases/tag/v0.9.2) of the provider with [#292](https://github.com/filecoin-project/index-provider/pull/292)
and here in https://github.com/filecoin-project/storetheindex/pull/1014 - which is rolled out to the cid.contact indexers.
