### ISSUE TITLE
Monthly cost tracking/update

### ISSUE THREAD

**Issue by honghaoq** [filecoin-project/storetheindex#717]
at https://www.notion.so/pl-strflt/Indexer-Cost-d8ce467167d7437eab4fd48be9624ec6

**Comment by masih** [comment]
is the ask here to upload the COGS from AWS to notion? I am curious; would it be simpler to log into AWS and see the COGS live?

**Comment by honghaoq** [comment]
That'd be better, can you share the link and account with me offline so I can log in to check, I can also update the notion monthly so others can check easily.
