### ISSUE TITLE
[TBD] Kubo to send records to the indexer by default, in addition to the DHT when providing to the network

### ISSUE THREAD

**Issue by honghaoq** [filecoin-project/storetheindex#722]
An option in discussion with IPFS steward: 
We first need to make this possible for Kubo to publish recrods with reframe and have the proper configuration knobs exposed.
Then work to show with numbers in the wild the benefit this has for users.
Then likely be a community topic to get input on it.

**Comment by willscott** [comment]
* step 1 is to get reframe work so we can with explicit config send records to a reframe endpoint, including an STI sidecar.
* step 2 would be a new gossip discovery protocol that kubo nodes could send on by default for auto-discovery of endpoints
* step 3 would be figuring out semantics of timing / who runs the ingest side, but this is quite long future.

i don't think you could really imagine a single instance of STI getting provider records from Kubo
