### ISSUE TITLE
Add ingest time per multihash metric

### ISSUE THREAD

**Issue by masih** [filecoin-project/storetheindex#744]
The time spent ingesting a batch of multihashes is logged by the ingester. Ingester also logs the size of the batch in a different line. To find out the normalised ingest time one has to do Loki query gymnastics like this:
```
sum(
sum_over_time ({environment="prod", namespace="storetheindex", pod_name=~"(dido|vega).+"} |~ "elapsed" | json | unwrap elapsed [1m])
) by (pod_name)

/

sum(
sum_over_time ({environment="prod", namespace="storetheindex", pod_name=~"(dido|vega).+"} |~ "Put multihashes in" | json | unwrap count [1m])
) by (pod_name)
```

Add a metric that reports the normalised ingest time per multihash for a processed batch.

**Comment by gammazero** [comment]
Should this measure the ingest time, meaning the time include how long it took to download it from the provider, or should this measure only the time to store a multihash after downloading it?

**Comment by masih** [comment]
Following the terminology above, this issue is about reporting `StoreTime`. 
Here is a metric definition that should hopefully tighten up what's needed here: 
* The elapsed time, starting from the time at which entries of an ad have been downloaded to the time at which that ad is marked as processed, _per multihash_.

The "per multihash" part is to normalise the elapsed time, such that the measurements across nodes are comparable:
* Today, looking at the ingest rate alone is not enough to get a good gauge of the velocity at which a node is ingesting, because each node may be ingesting from a different subset of providers.

**Comment by gammazero** [comment]
OK, that makes sense.  Now the problem is that the metrics we are using has a minimum time resolution of milliseconds and the time to store each multihash is sub-millisecond.  So, if I want to use an aggregate view, as we do for our other latency metrics, then we should probably have the metric be per 1000 multihashes. WDYT?
