### ISSUE TITLE
Remove indexed entries when a `remove` Advertisement is received

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/storetheindex#78]
As per [this TODO](https://github.com/filecoin-project/storetheindex/blob/c1e9a04d5b423e05be6572765ad92bbadd1d4591/internal/ingest/linksystem.go#L233), when we currently expect to receive the list of entries to remove inside the advertisement. This is not going to be the case in the future, as the provider may not know the list of multihashes that it is removing and the indexer will not have a way to ingest it. 

To overcome this, the indexer will use the `ContextID` from indexer core to identify the Entries CID a specific entry in the indexer corresponds to. Thus, when a remove Advertisement is received from a provider, the indexer iterates over the index to remove all the entries with a specific `ContextID` (using a similar implementation to the one used for `RemoveProvider' ).

This depends on:
- https://github.com/filecoin-project/go-indexer-core/issues/13
- https://github.com/filecoin-project/storetheindex/issues/56

**Comment by gammazero** [comment]
This should be handled by #104.  Complete this issue by providing verification in the end-to-end test.

**Comment by gammazero** [comment]
End-to-end testing of removal by contextID is done
