### ISSUE TITLE
Indexer nodes can pull from each other

### ISSUE THREAD

**Issue by honghaoq** [filecoin-project/storetheindex#819]
Nodes pulling from each other plus metric exposure

**Comment by gammazero** [comment]
This means that indexer nodes would need to save advertisement chains. This is what mirroring accomplishes.

Propose this issue be closed in favor of mirroring implementation.

**Comment by honghaoq** [comment]
Sounds good, is there an issue link for the mirroring implementation? is this the right one - https://github.com/filecoin-project/storetheindex/issues/674 @gammazero

**Comment by honghaoq** [comment]
Duplicate by mirror implementation
