### ISSUE TITLE
I have a curious question about  of  the number of indexes.

### ISSUE THREAD

**Issue by zhongdonglin** [filecoin-project/storetheindex#913]
Can I only know the number of indexes provided by the provider through this log information?

`2022-09-13T18:04:13.257Z        INFO    indexer/ingest  ingest/linksystem.go:537        Put multihashes in entry chunk  {"publisher": "12D3KooWDMJSprsuxhjJVnuQQcyibc5GxanUUxpDzHU74rhknqkU", "adCid": "baguqeerag4fgusrj7mpnthmrwzurnpczcwi5h5bzqfron4bbdz63tvirdhpa", "contextID": "AXESIFCboCLUGdLpDRX3DnFKL13y4pRG1VG6R1jrqRZBxyfT", "provider": "12D3KooWDMJSprsuxhjJVnuQQcyibc5GxanUUxpDzHU74rhknqkU", "entriesCid": "baguqeerafosejysge2nsekoblvrqjv5mrtzd5fuid35fgxztmushvrwrlumq", "entriesKind": "EntryChunk", "count": 16384}`

**Comment by willscott** [comment]
correct.

There is a rough estimate that datastores may provide that will be exposed at the `/stats` endpoint, but it is not guaranteed to be a precise count of entries.
